on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex

      - uses: actions/upload-artifact@v7
        with:
          name: resume-ianick-noejovich
          path: resume.pdf

      - uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: latest
          body: ${{ github.sha }}
          files: resume.pdf
          make_latest: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
